AWSTemplateFormatVersion: 2010-09-09
Description: Setup AWS Inspector to peform security scans
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: "Target Tags"
        Parameters:
          - tagkey
          - tagval
      -
        Label:
          default: "Inspector VPC Config"
        Parameters:
          - subnets
          - securitygroups

Parameters:
  tagkey:
    Type: String
    AllowedPattern: ".+"
    Description: Tag Key
  tagval:
    Type: String
    AllowedPattern: ".+"
    Description: Tag Value
  subnets:
    Type: List<AWS::EC2::Subnet::Id>
    AllowedPattern: ".+"
    Description: Subnets to Scan
  securitygroups:
    Type: List<AWS::EC2::SecurityGroup::Id>
    AllowedPattern: ".+"
    Description: Security Groups for Scanning

Resources:

  InspectorResourceGroup:
    Type: AWS::Inspector::ResourceGroup
    Properties:
      ResourceGroupTags:
        -
          Key: !Ref tagkey
          Value: !Ref tagval

  InspectorAssessmentTarget:
    Type: AWS::Inspector::AssessmentTarget
    Properties:
      AssessmentTargetName: !Sub ${AWS::Region}-AssessmentTarget
      ResourceGroupArn: !GetAtt InspectorResourceGroup.Arn

  InspectorTemplate:
    Type: AWS::Inspector::AssessmentTemplate
    Properties:
      AssessmentTargetArn: !GetAtt InspectorAssessmentTarget.Arn
      AssessmentTemplateName: CVEs-CIS-BestPractices-RuntimeBehavior-Analysis
      DurationInSeconds: 7200
      RulesPackageArns: # todo fix for cross region
        - "arn:aws:inspector:us-east-1:316112463485:rulespackage/0-gEjTy7T7" # https://docs.aws.amazon.com/inspector/latest/userguide/inspector_rules-arns.html
        - "arn:aws:inspector:us-east-1:316112463485:rulespackage/0-rExsr2X8"
        - "arn:aws:inspector:us-east-1:316112463485:rulespackage/0-R01qwB5Q"
        - "arn:aws:inspector:us-east-1:316112463485:rulespackage/0-gBONHN9h"
      UserAttributesForFindings:
        -
          Key: !Ref tagkey
          Value: !Ref tagval

  ScheduleSecurityInspections:
    Type: "AWS::Lambda::Function"
    Properties:
      Code:
        ZipFile: |
          import boto3
          client = boto3.client('inspector')
          def handler(event, context):
            response = client.list_assessment_targets()
            target = response["assessmentTargetArns"][0]
            target.encode('utf')
            templates = client.list_assessment_templates(
              assessmentTargetArns=[
                  target
              ]
            )
            describe = client.describe_assessment_templates(
              assessmentTemplateArns = templates["assessmentTemplateArns"]
            )
            client.start_assessment_run (
              assessmentRunName = describe[u'assessmentTemplates'][0][u'name'],
              assessmentTemplateArn = describe[u'assessmentTemplates'][0][u'arn']
            )
            return "success"
      Description: Schedule Security Inspections
      Handler: index.handler
      MemorySize: 128
      Role: !GetAtt InspectionExecutionRole.Arn
      Runtime: 'python2.7'
      Timeout: 60
      VpcConfig:
        SecurityGroupIds: !Ref securitygroups
        SubnetIds: !Ref subnets

  InspectorSchedule:
    Type: "AWS::Events::Rule"
    Properties:
      Description: Schedule Inspector Jobs
      ScheduleExpression: cron(0 17 * * ? *)
      Targets:
        -
          Arn:
            Fn::GetAtt:
              - "ScheduleSecurityInspections"
              - "Arn"
          Id: "ScheduleSecurityInspections"

  InspectionExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
            - ec2.amazonaws.com
          Action:
          - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaENIManagementAccess
        - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess
        - arn:aws:iam::aws:policy/AmazonInspectorFullAccess
Outputs:
  StackName:
    Description: The name of the stack
    Value: !Ref AWS::StackName